[[redirects]]
  from = "/proxy/*"
  to = "https://uxplorer-production.ap-northeast-2.elasticbeanstalk.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
